### ISSUE TITLE
Doesn't work with implicit/child gems

### ISSUE THREAD

**Issue by indirect** [bigrails/subbundle#2]
I can't quite tell if this is intended to work or not, but it surprised me because Bundler binstubs work even with gems that aren't explicitly in the Gemfile:

```
bundle init
bundle add subbundle
bundle add guard-rubocop
mkdir bin
echo 'unless defined?(Subbundle)
  require "bundler"

  Bundler.locked_gems.specs.find { |spec| spec.name == "subbundle" }&.tap do |subbundle|
    Gem.use_paths Gem.dir, Bundler.bundle_path.to_s, *Gem.path
    gem "subbundle", subbundle.version
    require "subbundle"
  end
end' > bin/subbundle

echo '# Load the subbundle binstub first.
load File.expand_path("subbundle", __dir__)
# Setup the subbundle.
Subbundle.setup("rubocop")

# Execute the binary.
load Gem.bin_path("rubocop", "rubocop")' > bin/rubocop

ruby bin/rubocop
/Users/andre/.gem/ruby/3.1.2/gems/bundler-2.3.11/lib/bundler/rubygems_integration.rb:319:in `block in replace_bin_path': can't find executable rubocop for gem rubocop. rubocop is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /Users/andre/.gem/ruby/3.1.2/gems/bundler-2.3.11/lib/bundler/rubygems_integration.rb:358:in `block in replace_bin_path'
        from bin/rubocop:7:in `<main>'
```

**Comment by ngan** [comment]
Hey @indirect -- this is known and intended...or rather, I didn't care to solve this because I think it's the right thing to do. Since rubocop isn't a direct dependency, you shouldn't have a binstub for it in the first place.

This is along the lines of having `require 'rubocop'` somewhere in your app but not having it defined as a direct dependency in your bundle/Gemfile.

**Comment by indirect** [comment]
This is a common pattern, unfortunately: the `rspec` command is provided by the `rspec-core` gem, not `rspec`. the `rails` command is provided by the `railties` gem, not `rails`. If subbundle doesn't support this, it's unfortunately a nonstarter to upstream into Bundler. :/

**Comment by ngan** [comment]
Ah! You're right. Let me take a crack at fixing this.

**Comment by ngan** [comment]
@indirect after the many recent performance enhancements in Bundler, we've decided not to use this gem anymore. Native `bundle/setup` now takes ~`0.5 seconds`. It use to take `3 seconds`.

I'll be archiving this repo.
